#general settings
name: 052_ESRGAN_gray_x4_03_  # grayscale images. 26 images. without perceputual and gan losses. weight 1.0.
model_type: SRModel
scale: 4
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 0
is_gray: true

# dataset and data loader settings
datasets:
  train:
    name: dataset_grayscale
    type: PairedImageDataset
    dataroot_gt: datasets/dataset_grayscale/gt
    dataroot_lq: datasets/dataset_grayscale/lq_x4
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 20
    prefetch_mode: ~

  val:
    name: dataset_grayscale
    type: PairedImageDataset
    dataroot_gt: datasets/dataset_grayscale/gt
    dataroot_lq: datasets/dataset_grayscale/lq_x4
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

# path
path:
  pretrain_network_g: experiments/051_gray_01_RRDBNet_PSNR_x4/models/net_g_565000.pth
  strict_load_g: true
  resume_state: experiments/052_ESRGAN_gray_x4_03_/training_states/285000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5
    # type: CosineAnnealingRestartLR
    # periods: [250000, 250000, 250000, 250000]
    # restart_weights: [1, 1, 1, 1]
    # eta_min: !!float 1e-7

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2.5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
