# general settings
name: train_SwinIR_SR_meta_upscale_scratch_P48W8_t2m_B1G4
model_type: SwinIRModel
# scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: t2m_train
    type: t2mDataset
    dataroot_gt: /mnt/ssd/sr/datasets/t2m_1940_1950/y
    dataroot_lq: /mnt/ssd/sr/datasets/t2m_1940_1950/x
    start_date: 19400101
    end_date: 19481231
    mean: 275.90152 
    std: 23.808582
    io_backend:
      type: disk

    # data loader
    num_worker_per_gpu: 16
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: t2m_val
    type: t2mDataset
    dataroot_gt: /mnt/ssd/sr/datasets/t2m_1940_1950/y
    dataroot_lq: /mnt/ssd/sr/datasets/t2m_1940_1950/x
    start_date: 19490101
    end_date: 19501231
    mean: 275.90152 
    std: 23.808582
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIRMetaUpsample
  upscale_v: !!float 7.510416666666667
  upscale_h: !!float 10
  in_chans: 1
  img_size: [96, 144]
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 90
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'meta'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
