# general settings
name: train_SwinIRGANMask_SR_meta_upscale_scratch_P48W8_sst_B1G1
model_type: SwinIRMetaUpsampleMaskedModel
# scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  val:
    name: sst_val
    type: sstDataset
    dataroot_gt: /mnt/ssd/sr/datasets/sst_1940_1950/y
    dataroot_lq: /mnt/ssd/sr/datasets/sst_1940_1950/x
    start_date: 19400101
    end_date: 19401231
    mean: 289.83038270488356
    std: 10.966654158164557
    io_backend:
      type: disk

  train:
    name: sst_train
    type: sstDataset
    dataroot_gt: /mnt/ssd/sr/datasets/sst_1940_1950/y
    dataroot_lq: /mnt/ssd/sr/datasets/sst_1940_1950/x
    start_date: 19410101
    end_date: 19511231
    mean: 289.83038270488356
    std: 10.966654158164557
    io_backend:
      type: disk

    # data loader
    num_worker_per_gpu: 16
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~



# network structures
network_g:
  type: SwinIRMetaMaskUpsample
  upscale_v: !!float 1.8776041666666667
  upscale_h: !!float 4.5
  in_chans: 1
  img_size: [384, 320]
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'meta'
  resi_connection: '1conv'

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 1
  num_feat: 64
  skip_connection: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  # perceptual loss (content and style losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  # gan loss
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1
    
  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    mse: # metric name, can be arbitrary
      type: calculate_mse
      crop_border: 4

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
