# general settings
name: 107_EDVRwoTSA_CBInit_lr1e-4_400k_REDS_SyncBN
use_tb_logger: true
model_type: VideoGANModel
scale: 4
num_gpu: 8

# datasets
datasets:
  train:
    name: REDS
    type: REDSDataset

    dataroot_gt: ../datasets/REDS/train_sharp
    dataroot_lq: ../datasets/REDS/train_sharp_bicubic
    dataroot_flow: ~
    meta_info_file: ./data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4
    io_backend:
      type: memcached
      server_list_cfg: /mnt/lustre/share/memcached_client/server_list.conf
      client_cfg: /mnt/lustre/share/memcached_client/client.conf
      sys_path: /mnt/lustre/share/pymc/py3

    num_frame: 5
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    use_shuffle: true
    num_worker: 3  # per GPU
    batch_size: 32
    dataset_enlarge_ratio: 1000

  val:
    name: REDS4
    type: VideoTestDataset
    dataroot_gt: ../datasets/REDS/REDS4/GT
    dataroot_lq: ../datasets/REDS/REDS4/sharp_bicubic
    io_backend:
      type: disk

    cache_data: True
    num_frame: 5
    padding: reflection_circle

# network structures
network_g:
  type: EDVR
  num_feat: 64
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  predeblur: false
  hr_in: false
  with_tsa: false

network_d:
  type: VGGStyleDiscriminator256
  num_in_ch: 3
  num_feat: 64
  syncbn: true


# path
path:
  pretrain_model_g: ../experiments/EDVRM_woTSA_scratch_REDS4/models/net_g_600000.pth
  strict_load: true
  resume_state: ~

# training settings: learning rate scheme, loss
train:
  lr_g: !!float 1e-4
  weight_decay_g: 0
  beta_g: [0.9, 0.99]
  lr_d: !!float 1e-4
  weight_decay_d: 0
  beta_d: [0.9, 0.99]
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: CharbonnierLoss
  pixel_weight: !!float 1e-2
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 1.0
    style_weight: 0
    norm_img: false
    criterion: l1
  gan_type: vanilla
  gan_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

  val_freq: !!float 20000
  val_func: VideoSRValidation

  manual_seed: 0

# logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000

dist_params:
  backend: nccl
  port: 29748
